### ISSUE TITLE
Publish existing gems

### ISSUE THREAD

**Issue by DerekStride** [Faveod/ruby-tree-sitter#23]
Since #22 any new published release will publish packages to rubygems. However, the existing packages need to be published manually.

@stackmystack could you download the built artifacts for the [latest release](https://github.com/Faveod/ruby-tree-sitter/releases/tag/v0.20.6.2) and publish them. 

It should be as simple as using `gem push` on each of the gem artifacts, you might need to login to rubygems or set the `RUBYGEMS_API_KEY` locally.

**Comment by stackmystack** [comment]
Hi Derek, I tried to do so like 2 days ago, and I still haven't found a solution to the problem I faced: when I want to push I get this:

```
Pushing gem to https://rubygems.org...
There was a problem saving your gem: Name 'tree_sitter' is too similar to an existing gem named 'tree-sitter'
```

And I don't know what to do. 

When I first started, I called the project `grenadier`, but I kind of dislike the `grenadier` name and then `require 'tree_sitter'` in code … 

I am not sure if we should get back to the older name or not, but if I decide to, it means requiring a different name than `tree_sitter` …

One possible solution is renaming the gem to `ruby_tree_sitter`, so `require 'tree_sitter'` is more "tolerable" .  But again, I don't know if `rubygems.org` would reject it on the same basis.

What do you think? 

Do you know if `rubygems.org` would make an exception for us given that the maintainers of `tree-sitter` are not actively working on it anymore and that this project is supposed to replace it?

**Comment by DerekStride** [comment]
Hmm, I was looking around and found a few posts to [help.rubygems.org](
https://help.rubygems.org/discussions/problems/38446-gem-push-says-there-is-already-too-similar-gem-name) but that site is deprecated. Instead it says to contact support@rubygems.com.

I'll send them an email to see if they will add `tree_sitter` to an allow-list. Another option is to ask if https://github.com/tree-sitter/ruby-tree-sitter.old would remove their outdated version of the gem.

**Comment by phsurette** [comment]
`ruby-treesitter-bindings` could be a good candidate name for the gem if it's not possible to remove the old gem.

**Comment by DerekStride** [comment]
I'd also be in favour of `ruby-tree-sitter` it's reflective of the git repository name and follows the conventions set by [java](https://github.com/serenadeai/java-tree-sitter), [python](https://github.com/tree-sitter/py-tree-sitter), [OCaml](https://github.com/returntocorp/ocaml-tree-sitter-core), & [haskell](https://github.com/tree-sitter/haskell-tree-sitter).

We can see if we get a response from the rubygems support team first though.

**Comment by stackmystack** [comment]
Thanks Derek. Helpful as always. Let's wait. We'll fallback to `ruby_tree_sitter` or `ruby-tree-sitter` (underscores seem more "rubyish" maybe?).

**Comment by DerekStride** [comment]
> Let's wait.

👍 

> underscores seem more "rubyish" maybe?

The ruby conventions for pathnames & constants are to use:

- `_` underscores when the file loads a constant with CapitalCase constants
- `-` dashes usually mean subdirectories & convert to nested constants e.g. `RootConstant::NestedConstant`

```ruby
require "my_gem-ruby" # equivalent to: require_relative "my_gem/ruby.rb"
MyGem::Ruby
```

For the actual gem name on rubygems it's less strict. I'd probably use underscores for at least the `tree_sitter` part though, since that would match the require pathname's (e.g. `require "tree_sitter"`) and the expected constants e.g.`TreeSitter`.

Something along the lines of:

```ruby
require 'bundler/inline'

gemfile do
  gem "ruby_tree_sitter"
  gem "ruby-tree_sitter" # alternative
  gem "tree_sitter-rb" # I've used the `-rb` suffix before
end

require "tree_sitter"
```

It's more aesthetic at that point though so I'll leave it to you to pick your favourite.

**Comment by phsurette** [comment]
Once this gets published it would be a good time to update [the official treesitter docs](https://github.com/tree-sitter/ruby-tree-sitter.old)

**Comment by stackmystack** [comment]
Hi @DerekStride,

I'm sorry it took me so long to move on with this.

I decided to go forward with `ruby_tree_sitter`, but the publish job [failed](https://github.com/Faveod/ruby-tree-sitter/actions/runs/4151349566/jobs/7181605454).

I think it doesn't recognise having different archs of the same name + version.

Are we sure we can publish the gems like this? If not, maybe we could just publish a normal gem that builds on install. I saw what the Nokogiri team was doing, and I think we're doing basically the same, no?

**Comment by DerekStride** [comment]
I think the different architectures are fine, it's when it's trying to push a packaged gem that was built with a different version of ruby that it failed. I describe a fix for the issue here: https://github.com/Faveod/ruby-tree-sitter/pull/24

You'll likely want to yank the existing gems a published @ https://rubygems.org/gems/ruby_tree_sitter before trying again or it'll fail.

Alternatively, you can manually push the `ruby_tree_sitter-0.20.6.3-x86_64-linux-mri-3.2.gem` from the release (I think that's the only one missing): https://github.com/Faveod/ruby-tree-sitter/releases

**Comment by stackmystack** [comment]
Gems published.
