### ISSUE TITLE
Where is init_fields defined?

### ISSUE THREAD

**Issue by akimd** [Faveod/ruby-tree-sitter#28]
node.rb reads

```ruby
    def respond_to_missing?(*args)
      init_fields
      args.length == 1 && fields.include?(args[0])
    end
```

When trying the Python parser for instance, we enter this routine, and die for lack of definition of init_fields.

Maybe exposing "fields" directly as method names was a dubious idea, I don't know.

**Comment by stackmystack** [comment]
It was defined before refctoring, e.g. [here](https://github.com/Faveod/ruby-tree-sitter/blob/4f97e9541c28d748b89fca99b16d9606ddfe6ccf/lib/tree_sitter/node.rb#L7).

I will remove it. Thanks.
